name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Usar variável secreta
        run: echo "Deploy token: $RENDER_TOKEN"

      - name: Deploy (fake)
        run: curl -X POST $RENDER_DEPLOY_HOOK

      - name: Gerar arquivos
        run: |
          # dica em "hash" (ASCII → texto)
          echo "100 105 99 97 58 32 116 114 111 113 117 101 32 97 32 112 97 108 97 118 114 97 32 101 115 116 117 100 111 32 112 111 114 32 101 115 116 117 100 97 100 111" \
          | awk '{for(i=1;i<=NF;i++) printf "%c",$i}' > dica.txt

          # resultado em "hash" (ASCII → texto)
          echo "97 32 97 117 108 97" \
          | awk '{for(i=1;i<=NF;i++) printf "%c",$i}' > resultado.txt

      - name: Expor resultados
        run: |
          cat dica.txt
          echo ""
          cat resultado.txt